version: "3.3"

services:
  java_container:
    image: openjdk:8
    container_name: "java-container"
    restart: always
    ports:
      - 8091:8091
    volumes:
          #path to jar file /opt/jar_app/app.jar
      - "/opt/jar_app/:/usr/app"
    command: ['java', '-jar', '/usr/app/app.jar']
  postgres_container:
    image: postgres:13.8-alpine
    volumes:
      - /opt/postgres/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django_container:
    build: /opt/django_app/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /opt/django_app:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres_container